#ifndef GLOBALS_H
#define GLOBALS_H

const int WIDTH = 640;
const int HEIGHT = 480;

enum ID{ PLAYER, ENEMY, BORDER, MISC, ANIMATIONS };
enum STATE{ TITLE1, TITLE2, END, CREDIT, BOSSTALK, CONVERSATION, LOAD1, LOAD2, PLAYING, BOSS, VICTORY, STATUS, LOST, MAIN, OPTION, SAVE, ITEM, MAGIC, EQUIP, LOCAL, WORLD, SHOP, BUY, SELL, GAMBLE, BATTLE, BATTLE2, CONFIG, ABOUT, LEVEL2, WORLD_MAIN, BOSS2, BOSS3 };
#endif
